In [80]:
import pandas as pd
from IPython.display import display
import numpy as np

In [81]:
pd.set_option("display.max_rows", None)
pd.set_option('future.no_silent_downcasting', True)

In [82]:
df= None
minvotes= None

In [147]:
def read_file(path):
    global df
    df= pd.read_csv(path)
def cleanData():
    global df
    df= df.drop(["year"],axis=1)
    df= df.drop(["kind"],axis=1)
    df= df.drop(["runtime"],axis=1)
    df= df.drop(["cast"],axis=1)
    df= df.drop(["director"],axis=1)
    df= df.drop(["composer"],axis=1)
    df= df.drop(["writer"],axis=1)
    df= df.drop(["Unnamed: 0"],axis=1)
    df=df.drop_duplicates(subset='title')
    df= df.fillna(0)
def filter_genre(genre):
    global df
    df= df[df['genre'].str.contains(genre, case=False,).fillna(False)] 
def Thresh_votes(thrs):
    global df
    global minvotes
    q= np.quantile(df['vote'],thrs)
    df = df.drop(df[df.vote < q].index)
    minvotes=q
    
def avg_score():
    global df
    mean = df['rating'].mean()
    print(mean)
    avg=[]
    df = df.reset_index(drop=True)
    for i in range(0,len(df['rating'])):
        res= (df['vote'][i]/(df['vote'][i]+minvotes)*df['rating'][i])+ (minvotes/(df['vote'][i]+minvotes))*mean
        avg.append(res)
    df['Weighted Average'] = (avg)
def sort_score(n):
    sort= df.sort_values('Weighted Average',ascending= False).head(n)
    sort=sort.reset_index(drop=True)
    display(sort)
def runRecomenderSystem(genre,votesThrs,NumberOfReturnedData):
    read_file("C:\\Users\dell\\Desktop\\CV\\Python\\Kurs\\27. Netflix recomendation\\imdb.csv")
    #pre-proces
    cleanData()
    #filter
    filter_genre(genre)


    Thresh_votes(votesThrs)
    avg_score()
    sort_score(NumberOfReturnedData)

In [150]:
runRecomenderSystem("Drama",0.8,5)

7.307142857142857

,title,genre,rating,vote,country,language,Weighted Average
0,Band of Brothers,"['Action', 'Drama', 'History', 'War']",9.4,398551.0,"['United States', 'United Kingdom']","['English', 'Dutch', 'French', 'German', 'Lith...",9.323076
1,The Shawshank Redemption,['Drama'],9.3,2461873.0,['United States'],['English'],9.287765
2,Game of Thrones,"['Action', 'Adventure', 'Drama', 'Fantasy']",9.2,1873254.0,"['United States', 'United Kingdom']",['English'],9.184757
3,The Godfather,"['Crime', 'Drama']",9.2,1702698.0,['United States'],"['English', 'Italian', 'Latin']",9.183243
4,Fullmetal Alchemist: Brotherhood,"['Animation', 'Action', 'Adventure', 'Comedy',...",9.1,138675.0,['Japan'],['Japanese'],8.922815

In [190]:
class NetflixRecomennderSystem:
    def  __init__(self,dataset,genre,votesThrs,topN):
        self._dataset = dataset
        self._genre = genre
        self._votesThrs= votesThrs
        self._topN = topN
        self.df= None
        self._minvotes= None
        
    def read_file(self):
        self.df= pd.read_csv(self._dataset)
    def cleanData(self):
        self.df= self.df.drop(["year"],axis=1)
        self.df= self.df.drop(["kind"],axis=1)
        self.df= self.df.drop(["runtime"],axis=1)
        self.df= self.df.drop(["cast"],axis=1)
        self.df= self.df.drop(["director"],axis=1)
        self.df= self.df.drop(["composer"],axis=1)
        self.df= self.df.drop(["writer"],axis=1)
        self.df= self.df.drop(["Unnamed: 0"],axis=1)
        self.df=self.df.drop_duplicates(subset='title')
        self.df= self.df.fillna(0)
    def filter_genre(self):
        self.df= df[df['genre'].str.contains(self._genre, case=False,).fillna(False)] 
    def Thresh_votes(self):
        self._minvotes= np.quantile(self.df['vote'],self._votesThrs)
        self.df = self.df.drop(self.df[self.df.vote < self._minvotes].index)
    def avg_score(self):
        mean = self.df['rating'].mean()
        print(mean)
        avg=[]
        self.df = self.df.reset_index(drop=True)
        for i in range(0,len(self.df['rating'])):
            res= (self.df['vote'][i]/(self.df['vote'][i]+self._minvotes)*self.df['rating'][i])+ (self._minvotes/(self.df['vote'][i]+self._minvotes))*mean
            avg.append(res)
        self.df['Weighted Average'] = (avg)
    def sort_score(self):
        sort= self.df.sort_values('Weighted Average',ascending= False).head(self._topN)
        sort=sort.reset_index(drop=True)
        display(sort)
    def run(self):
        self.read_file()
        self.cleanData()
        self.filter_genre()
        self.Thresh_votes()
        self.avg_score()
        self.sort_score()

In [191]:
path= "C:\\Users\dell\\Desktop\\CV\\Python\\Kurs\\27. Netflix recomendation\\imdb.csv"
best5Comedy= NetflixRecomennderSystem(path,"Comedy",0.8,5)

In [192]:
best5Comedy.run()

7.36086956521739

,title,genre,rating,vote,country,language,Weighted Average
0,Parasite,"['Comedy', 'Drama', 'Thriller']",8.6,658561.0,['South Korea'],"['Korean', 'English']",8.419261
1,Fullmetal Alchemist: Brotherhood,"['Animation', 'Action', 'Adventure', 'Comedy',...",9.1,138675.0,['Japan'],['Japanese'],8.321202
2,The Truman Show,"['Comedy', 'Drama']",8.1,988070.0,['United States'],['English'],8.024470
3,Dead Poets Society,"['Comedy', 'Drama']",8.1,448613.0,['United States'],"['English', 'Latin']",7.951850
4,The Graduate,"['Comedy', 'Drama', 'Romance']",8.0,262646.0,['United States'],['English'],7.808382

In [193]:
path = "imdb.csv"

best5Comedy = NetflixRecomennderSystem(
    path, "Comedy", 0.8, 5
)

best5Comedy.run()

7.36086956521739

,title,genre,rating,vote,country,language,Weighted Average
0,Parasite,"['Comedy', 'Drama', 'Thriller']",8.6,658561.0,['South Korea'],"['Korean', 'English']",8.419261
1,Fullmetal Alchemist: Brotherhood,"['Animation', 'Action', 'Adventure', 'Comedy',...",9.1,138675.0,['Japan'],['Japanese'],8.321202
2,The Truman Show,"['Comedy', 'Drama']",8.1,988070.0,['United States'],['English'],8.024470
3,Dead Poets Society,"['Comedy', 'Drama']",8.1,448613.0,['United States'],"['English', 'Latin']",7.951850
4,The Graduate,"['Comedy', 'Drama', 'Romance']",8.0,262646.0,['United States'],['English'],7.808382